### ISSUE TITLE
Please add support for flood sensor 

### ISSUE THREAD

**Issue by bliekp** [TedTolboom/com.xiaomi-mi-zigbee#131] opened 2019-02-04 11:09 UTC
Please add support for the flood sensor. 

€ 11,13  58％ Off | 2018 Newest Xiaomi Mijia Aqara Water Immersing Sensor Flood Water Leak Detector for Home Remote Alarm Security Soaking Sensor
https://s.click.aliexpress.com/e/cqmZYxIs

**Comment by chinswain** [comment] 2019-02-04 11:12
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/26

**Comment by TedTolboom** [comment] 2019-02-10 11:46
Duplicate of #26

**Closed by TedTolboom** 2019-02-10 11:46 UTC
