### ISSUE TITLE
Aqara Wireless Remote Switch Single as Unknown device

### ISSUE THREAD

**Issue by StraDijk** [TedTolboom/com.xiaomi-mi-zigbee#20] opened 2017-12-27 07:51 UTC
When i add the Aqara Wireless Remote Switch Single, it shows as unknown device.

![2017-12-27_08-48-02](https://user-images.githubusercontent.com/2519741/34374779-32c4e2e6-eae3-11e7-8ed4-0900a3807dcc.png)

**Comment by TedTolboom** [comment] 2017-12-27 08:54
@StraDijk if it is added as a generic ZigBee device, it is not (yet) supported by the app; no driver defined...

This can be caused by 2 things; either the device driver is not added yet (correct picture should not be visible on the app page at apps.athom.com) or the ID’s added are incomplete...

Considering the product ID, I think it is the first case..

To avoid confusion on different Ali or GearBest names; Can you indicate which device you are referring to based on the names used at the manufacturers site: https://xiaomi-mi.com/sockets-and-sensors/ ?

**Comment by StraDijk** [comment] 2017-12-27 10:23
@TedTolboom 
This is the one.
https://xiaomi-mi.com/sockets-and-sensors/aqara-smart-light-wall-switch-zigbee-version-single-key/

**Comment by TedTolboom** [comment] 2017-12-27 12:24
That one is not supported yet...

I do have the double switch myself; so once I have this one (double switch) working, I’ll be able to add the single switch version based on your ID numbers..

**Comment by TedTolboom** [comment] 2018-01-14 11:24
@StraDijk support will be added in the next app update...
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/commit/606189d421e5cc3c3017029555e9a11b269718f1

**Comment by StraDijk** [comment] 2018-01-22 20:15
Thank you!

**Comment by TedTolboom** [comment] 2018-02-15 06:30
@StraDijk would you be able to test a GitHub version (install via command line)?
I'd like to add these ID's to the existing driver, first test before releasing it to the app store

**Comment by StraDijk** [comment] 2018-02-15 08:26
No problem. Will test it when i get home.

**Comment by TedTolboom** [comment] 2018-03-08 22:37
@StraDijk can you let me know if the issue has been resolved with v0.2.4 as available in the app store?

**Comment by StraDijk** [comment] 2018-03-10 18:01
Yes, the issue is resolved. Thank you!

**Comment by TedTolboom** [comment] 2018-03-12 22:19
OK, thanks for the feedback. Closing issue, please re-open if something is still incorrect.

**Closed by TedTolboom** 2018-03-12 22:19 UTC
Labels: add deviceID, staged for release, waiting for user feedback
