### ISSUE TITLE
Wrong switch activating

### ISSUE THREAD

**Issue by Rockhoppers1964** [TedTolboom/com.xiaomi-mi-zigbee#64] opened 2018-05-07 07:00 UTC
I have two wall double switches right next to each other and have had range problems before when i had three in line.
Removed one and the other two now work, don't understand why ?

Recent problem is that there is an PIR outside the back door and when triggered i want it to turn on the outside light connected to one of the switches.

The first time i tried this, the switch next to it activated and turned on an internal light.
I checked the Flow and it is right.
I checked i can turn the correct switch on and off from within the devices menu in Homey, i can, no problems.

Thought there may be some address conflict (clutching at straws) so unpaired and then repaired and because that made no difference I then changed the unit completely, for a new switch. No change, when the flow tries to trigger the correct switch, the incorrect switch triggers.

Totally confused and checked everything many times, it all appears right [!]

Screen shots below.

Wall switches are doubles, and 1/2 means left and right buttons.

Andrew 

![capture01](https://user-images.githubusercontent.com/37954974/39688835-7211d210-51cc-11e8-8310-c3328794b3bc.JPG)
![capture02](https://user-images.githubusercontent.com/37954974/39688836-722c4c4e-51cc-11e8-80d2-f5bee4f65748.JPG)
![capture03](https://user-images.githubusercontent.com/37954974/39688838-724d0c4a-51cc-11e8-9f32-9bccbfb32de8.JPG)
![capture04](https://user-images.githubusercontent.com/37954974/39688839-72708044-51cc-11e8-82c4-b7e02e2a03fd.JPG)

**Comment by TedTolboom** [comment] 2018-05-07 21:45
@Rockhoppers1964 just to check if I understand the issue correctly...

For switch 1/2, you try with above flow to switch on the left switch (1 in your numbering) and it actually switches the right switch. Whereas if you toggle `switch 1` on the devices card, it does switch correctly?
<img width="342" alt="schermafbeelding 2018-05-07 om 23 39 39" src="https://user-images.githubusercontent.com/17163431/39726694-2f34829c-5250-11e8-8c00-2ec43f83175a.png">
 
If you try it the other way around, change the flow to switch the right switch (2), with the `Turn On Right Switch` card; which switch is then activated? Right or Left?
<img width="261" alt="schermafbeelding 2018-05-07 om 23 40 12" src="https://user-images.githubusercontent.com/17163431/39726752-61cc0e50-5250-11e8-88fe-fe7154084e4b.png">

When switching `switch 2` on the devices card, the right switch is activated correctly?

Which version of the Xiaomi app and Homey SW version do you have installed?

@addwindtan can you check this one?

**Comment by Rockhoppers1964** [comment] 2018-05-09 01:29
Ted, the issue is wider than that, i have two double wall switches next to each other.
So first wall switch has switch numbers 1 (left) and 2 (right) the second has numbers 3 (left) and 4 (right)
When i try and activate switch 2 (on wall switch 1) i get switch 4 (on wall switch two) coming on instead.
Can activate correctly through the devices menu, but not using flows.
Does that make sense ?
Andrew

**Comment by addwindtan** [comment] 2018-05-09 02:17
@Rockhoppers1964 I just tested on my setup at home and the action cards on the flow for both left and right buttons behave as required. However, I have only 1 double wall switch for my test.

Could you unpair switch 3/4 first and see if you have the same problem on switch 1/2?

**Comment by TedTolboom** [comment] 2018-05-11 08:28
@addwindtan I'm able to reproduce it...

Only on the second (right) switch, when activating from a flow card, the latest initialized device will be activated... so it looks like the device instance is not correctly linked to the flow card...

**Comment by Rockhoppers1964** [comment] 2018-05-11 13:31
Is that an issue with my flow ?

**Comment by addwindtan** [comment] 2018-05-11 14:41
I was not aware that we had to take care of the instance at the driver level. @TedTolboom Do you have some sort of a sample code I can refer to to help me fix the bug?

**Comment by TedTolboom** [comment] 2018-05-12 19:33
@addwindtan see https://developer.athom.com/docs/apps/tutorial-Flow-Arguments.html
In this example the flow card is registered on driver level... I'd like to propose to add the card on app level; similar to the trigger cards of the wireless switches...

But let me have a look into it... already have been working on the driver in parallel to working on #60

**Comment by TedTolboom** [comment] 2018-05-13 20:30
@Rockhoppers1964 found the bug and corrected it in above mentioned commit towards the development branch. Tested on my 2 switches and all switches are working correctly.

@addwindtan on code changes: moved the flow cards (for now) to the app level and added the right device instance to the runListener. In addition, I changed the EndPoints used for the attributeListeners back to 1 and 2. These endpoints provide the actual state of the device, simplifying the device driver (currently commented out the redundant sections).

Next steps will be to check the solution for issue #60; potentially I'll need to split the device driver and since that will also impact the same action cards, I'd prefer to do that in one go..
In addition, I'll need to bring the `ctrl_neutral1` device driver to the same state (minor update).

**Comment by TedTolboom** [comment] 2018-05-16 21:25
@Rockhoppers1964 @addwindtan issue has been fixed and running fine on my setup (2x switch).
Full updated app is available in the development branch: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/tree/development

If you would have a change to test this version in addition, I would appreciate that.
Please note the changelog in the readme, for this issue you will need to rebuild the flows

**Comment by Rockhoppers1964** [comment] 2018-05-25 07:17
Ted, not sure how i do that ?

**Comment by Rockhoppers1964** [comment] 2018-06-02 05:54
When is this going to be released Ted, this (and a load of other homey issues) is driving my wife mad now and pushing me to dump Homey and go for another system.

**Comment by TedTolboom** [comment] 2018-06-02 06:45
I will push it to the App Store this weekend

**Comment by TedTolboom** [comment] 2018-06-03 20:10
v0.4.0, including the fix for this issue, has been uploaded to the app store for approval.
I will close this issue for now. If the issues persists, please re-open

**Closed by TedTolboom** 2018-06-03 20:10 UTC
Labels: bug, staged for release
