### ISSUE TITLE
text too long to read on buttons

### ISSUE THREAD

**Issue by glennhmjoat** [TedTolboom/com.xiaomi-mi-zigbee#119] opened 2018-12-31 20:44 UTC
On Honey 2.0.0.rc9 with the temperature and humidity sensor.
In the advanced setting for it, there are two options, the details of what they are is hidden off the end of the buttons
![report temp](https://user-images.githubusercontent.com/45816076/50567478-2ce02800-0daa-11e9-9d56-2002e1bfc8fc.jpg)
![advanced](https://user-images.githubusercontent.com/45816076/50567488-51d49b00-0daa-11e9-9379-562874c08b42.jpg)

**Comment by TedTolboom** [comment] 2019-01-01 09:11
Duplicate of https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/115

**Closed by TedTolboom** 2019-01-01 09:11 UTC
