### ISSUE TITLE
Aqara (Single / Double) Wall Switch With Null not working

### ISSUE THREAD

**Issue by SadhuRus** [TedTolboom/com.xiaomi-mi-zigbee#60] opened 2018-04-23 10:43 UTC
The device is added normally. However, for some reason, only one button works programmatically. (Through Homey) The second will change the trigger, but the light does not change. Hardware buttons both work correctly. What could be the problem?

Product Id: lumi.ctrl_ln2.aq1
Device Id: 81
Profile ID: 260

Plugin version: 0.2.4

**Comment by SadhuRus** [comment] 2018-04-23 11:29
After enable DubugMode in logs:

`2018-04-23 14:27:59 [log] [ManagerDrivers] [ctrl_neutral2] [0] set onoff -> true
2018-04-23 14:27:59 [log] [ManagerDrivers] [ctrl_neutral2] [0] [AqaraLightControlDouble] [switchCapabilityListener] Received capabilityId = onoff  value =  true
2018-04-23 14:28:05 [log] [ManagerDrivers] [ctrl_neutral2] [0] set onoff.1 -> true`

**Comment by TedTolboom** [comment] 2018-05-06 07:33
@SadhuRus @Romast-Kirov looks like this is a driver issue... 

Some explination: I've added support for the Aqara wired switches based on a single driver (ctrl_neutral2) and tested it with the Aqara wall switch double (without neutral), with product ID: QBKG03LM (and Zigbee ID: lumi.ctrl_neutral2)...

The idea behind one driver, was my (now proven wrong) estimate that the wall switch with and without NULL would have the same control mechanism... both issues show that it doesn't...

So I will need to create a new driver for the switches with Null (Zigbee ID's lumi.ctrl_ln1.aq1 and lumi.ctrl_ln2.aq1)... 

@SadhuRus @Romast-Kirov is it possible to add a picture to this issue of the backside of both the single and double wall switch, showing also the product ID's (and specifications)?

Remote debugging is quite difficult in the current Zigbee implementation... 
But I will receive an identical double switch within 1 - 1.5 weeks to be able to debug myself.

@SadhuRus since you posted the debug log, could you take the following action:
On the double switch:
1) uncomment (remove the `// ` on) line https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L11
2) uncomment (remove the `// ` on) line https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L14
3) save the file
On the single switch (if available):
4) uncomment (remove the `// ` on) line https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral1/device.js#L11
5) uncomment (remove the `// ` on) line https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral1/device.js#L14
6) save the file
7) Run the file in debug mode `Athom project run`
8) post the node overviews (similar to https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L155) of both devices to this issue

**Comment by Romast-Kirov** [comment] 2018-05-06 18:58
Hi!!!
One key switch.
![img_0337](https://user-images.githubusercontent.com/38797231/39676759-8d4d7ed4-5178-11e8-8dc4-c2ca3f8e4a6f.JPG)

**Comment by Romast-Kirov** [comment] 2018-05-06 18:59
Two keys switch.
![img_0336](https://user-images.githubusercontent.com/38797231/39676774-a7d8ca92-5178-11e8-9aab-40319743974e.JPG)

I can give remote access for debugging!!!!
Thanks!!!

**Comment by TedTolboom** [comment] 2018-05-07 22:01
@Romast-Kirov thanks for posting the pictures...
So it is the QBKG11LM and QBKG12LM for the single and double switch with neutral and load up to 2500W

The offered remote access is appreciated, but will not provide much more detail. Part of the information I need is originating from a Zigbee Sniffer... which doesn't have a big enough range ;-P

So fastest option it to get one of these switches myself...

**Comment by TedTolboom** [comment] 2018-05-13 20:33
Brief update, I've received the switch so I will be able to test the issue myself in the next days.

In addition, I found the cause of the #64 issue and fixed that in the device driver that both devices have in common... this already might fix this issue or contribute to fixing this issue...

**Comment by SadhuRus** [comment] 2018-05-14 16:10
Hello! I apologize for the long absence.
Incorporated Dubug mode. Here are the logs:

After Adding:
`2018-05-14 18:59:11 [log] [ManagerDrivers] [ctrl_neutral2] [0] ZigBeeDevice has been inited
2018-05-14 18:59:11 [log] [ManagerDrivers] [ctrl_neutral2] [0] ------------------------------------------
2018-05-14 18:59:11 [log] [ManagerDrivers] [ctrl_neutral2] [0] Node: 2cabf860-d8a1-4c64-902a-f88a0693a7be
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Battery: false
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBasic
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBasic
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- zclVersion : 1
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- appVersion : 31
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- stackVersion : 2
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- hwVersion : 18
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- manufacturerName : LUMI
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- modelId : lumi.ctrl_ln2.aq1
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- dateCode : 10-12-2017
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- powerSource : 1
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genPowerCfg
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genPowerCfg
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- mainsVoltage : 2144
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genDeviceTempCfg
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genDeviceTempCfg
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- currentTemperature : 25
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genIdentify
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genIdentify
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- identifyTime : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genGroups
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genGroups
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- nameSupport : 128
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genScenes
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genScenes
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- count : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- currentScene : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- currentGroup : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sceneValid : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- nameSupport : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- lastCfgBy : 0xffffffffffffffff
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genOnOff
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genOnOff
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- onOff : 1
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genTime
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genTime
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genOta
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genOta
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 1
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genOnOff
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genOnOff
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- onOff : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 2
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genGroups
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genGroups
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genAnalogInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- 261 : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- 262 : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genAnalogInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 13.020000457763672
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- applicationType : 589824
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 3
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genAnalogInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- 261 : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- 262 : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genAnalogInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 1.2261933088302612
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- applicationType : 720896
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 4
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genMultistateInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genMultistateInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- numberOfStates : 6
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 5
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genMultistateInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genMultistateInput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- numberOfStates : 6
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] - Endpoints: 6
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] -- Clusters:
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- zapp
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genBinaryOutput
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:12 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] --- genMultistateInput
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- cid : genMultistateInput
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- sid : attrs
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- numberOfStates : 6
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- outOfService : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- presentValue : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ---- statusFlags : 0
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] ------------------------------------------
2018-05-14 18:59:13 [err] [ManagerDrivers] [ctrl_neutral2] [0] TypeError: Cannot read property 'read' of undefined
    at AqaraWallSwitchDouble._getCapabilityValue (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:160:19)
    at AqaraWallSwitchDouble._registerCapabilityGet (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:93:9)
    at AqaraWallSwitchDouble.registerCapability (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:375:8)
    at AqaraWallSwitchDouble.onMeshInit (/drivers/ctrl_neutral2/device.js:24:8)
    at AqaraWallSwitchDouble.once (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:51:28)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at AqaraWallSwitchDouble.emit (events.js:208:7)
    at process.nextTick (/node_modules/homey-meshdriver/lib/MeshDevice.js:43:11)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:13391) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: invalid_endpoint_cluster_combination
(node:13391) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: invalid_endpoint_cluster_combination
2018-05-14 18:59:13 [log] [ManagerDrivers] [ctrl_neutral2] [0] registerAttrReportListener() -> configured attr reporting attrReport_1_genOnOff_onOff

`

After right button:
`2018-05-14 19:00:29 [log] [ManagerDrivers] [ctrl_neutral2] [0] [AqaraLightControlDouble] [switchOneAttrListener] Received data = 0
2018-05-14 19:00:29 [log] [ManagerDrivers] [ctrl_neutral2] [0] [AqaraLightControlDouble] [switchOneAttrListener] Received data = 0
2018-05-14 19`


Left button not work in athom interface.. No logs((

Unfortunately I do not now have no opportunity to take a picture of the back cover (Since the European grid is not a Chinese one, I had to break the sub-label and glue it with glue, but I do not want to break this structure.

Also tried the last commit.(4dcea4c) Did not help

**Comment by TedTolboom** [comment] 2018-05-14 17:07
@sadhurus Thanks for providing the debug logging... 
based on this logging I already notice that that this switch uses Endpoint 0 and 1 for left and right switch, whereas the other switch uses respectively Endpoint 1 and 2...

I’ll verify with the switch I have at home...

**Comment by TedTolboom** [comment] 2018-05-14 17:46
You can already try this by changing the following based on the latent development branch:
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/development/drivers/ctrl_neutral2/device.js#L18

On L18 and L21, change 1 into 0
On L25 and L28, change 2 into 1
Save and re-run and the device should work...

Considering the differences between both switches, I will need to split the drivers... so re-pairing will be needed with the app update

**Comment by SadhuRus** [comment] 2018-05-15 17:57
Yes!! Now work fine!!! Thank you so much!!!

**Comment by TedTolboom** [comment] 2018-05-16 21:26
@SadhuRus @Romast-Kirov  issue has been fixed and running fine on my setup.
Full updated app is available in the development branch: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/tree/development

If you would have a change to test this version in addition, I would appreciate that.
Please note the change-log in the readme, for this issue you will need to re-include these type of switches to start using the right device driver.

**Comment by Romast-Kirov** [comment] 2018-05-17 07:51
@TedTolboom 
Forgive me for the stupid question, but how to  https://github.com/TedTolboom/com.xiaomi-mi-zigbee/tree/development update from here?

**Comment by TedTolboom** [comment] 2018-06-03 20:11
v0.4.0, including the fix for this issue, has been uploaded to the app store for approval.
I will close this issue for now. If the issues persists, please re-open

**Closed by TedTolboom** 2018-06-03 20:11 UTC
Labels: bug, staged for release
