### ISSUE TITLE
Do not work switches Aqara

### ISSUE THREAD

**Issue by Romast-Kirov** [TedTolboom/com.xiaomi-mi-zigbee#63] opened 2018-05-04 19:22 UTC
Kind time!!!!
Having seen enough video in network I have decided to construct the "clever house" on atom.
I have slowly bought sensors, Aqara switches have come today.
And here a problem, they are added, but don't react on any actions with athom, only physical pressing switches works.
If to switch-off Xiaomi Mi ZigBee and to connect switches simply as ZigBee that inclusion switching off works with athom. At addition of the two-gang switch through athom only one key works.
Xiaomi Mi ZigBee v0.3.0 version
Version of Atom 1.5.9
Thanks in advance for the help.

**Comment by SadhuRus** [comment] 2018-05-05 08:49
Absolutely identical problem. Need help!

**Comment by TedTolboom** [comment] 2018-05-05 09:56
Can you provide more details (product numbers / ID’s in Homey) / pictures of the switch you are trying to operate

**Comment by Romast-Kirov** [comment] 2018-05-05 12:46
Hi!!! Thanks for a response!!!

The rocker switch, with a zero phase.
If to add him with Xiaomi Mi ZigBee, then he is added, but doesn't work with athom.
Having added as ZigBee works.
![1](https://user-images.githubusercontent.com/38797231/39663393-6b7442f0-507b-11e8-888e-f662b7fb51f2.jpeg)
![2](https://user-images.githubusercontent.com/38797231/39663394-74239c7a-507b-11e8-8290-e6d11704d29b.jpeg)
![img_8050](https://user-images.githubusercontent.com/38797231/39663397-7d570584-507b-11e8-9793-755a17deca0e.JPG)

**Comment by Romast-Kirov** [comment] 2018-05-05 12:47
The two-gang switch if to add with Xiaomi Mi ZigBee, then it is defined too, but only one button works with athom.
Having added as ZigBee appears in athom only one button, there is no second.
![3](https://user-images.githubusercontent.com/38797231/39663408-9d64ce1a-507b-11e8-9ba2-e4b23491e77f.jpeg)
![4](https://user-images.githubusercontent.com/38797231/39663411-a3be7112-507b-11e8-9c76-600e623ea1dd.jpeg)
![img_1680](https://user-images.githubusercontent.com/38797231/39663415-ab48bdac-507b-11e8-9705-0abfd15792a5.JPG)

**Comment by Romast-Kirov** [comment] 2018-05-05 12:49
Not purebred switches, only one could add, I can't include the others in athom.
But both keys work.
![5](https://user-images.githubusercontent.com/38797231/39663429-e93c1da2-507b-11e8-80c1-ded5f1140b84.jpeg)
![img_9983](https://user-images.githubusercontent.com/38797231/39663430-ec649acc-507b-11e8-9250-cab52c50e547.JPG)

**Comment by TedTolboom** [comment] 2018-05-06 07:06
@Romast-Kirov thanks for providing the additional details; is indeed a duplicate of #60 
I will close this issue and will follow-up on #60, ok?

**Closed by TedTolboom** 2018-05-06 07:06 UTC
