### ISSUE TITLE
Aqara Smart plug (EU) Energy usage not being updated

### ISSUE THREAD

**Issue by epjjansen** [TedTolboom/com.xiaomi-mi-zigbee#231] opened 2020-10-12 12:14 UTC
The Aqara Smart plug (EU) does not update the total amount of energy being used in kWH.

Homey: V5.0.0-rc.34
Aqara & Xiami Zigbee App:  v1.1.4 (experimental)

**Comment by alexfost** [comment] 2020-10-14 06:05
I can confirm that for the Xiaomi Smart Plug (EU) I See the Same behaviour. Sadly the power consumption is not available in the homey app. On the plug page you can only see "-" for both energy counters.


Homey Pro 4.2
SW 6.1.0.633
App v0.8.8

**Comment by dutchdevil83** [comment] 2020-10-18 09:59
have also these plugs. Maybe looking at ZHA will help to integrate this with the power options? Looks like the AnalogInput is needed to relay all information to the ElectricalMeasurement cluster and the values are coded with this Hex ID:
    POWER_ID = 0x050B
    VOLTAGE_ID = 0x0500
    CONSUMPTION_ID = 0x0304

[https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/xiaomi/__init__.py]

**Comment by alexfost** [comment] 2020-10-18 10:06
Thanks for the quick response. 
Good News: after some days (and several Home restarts due to other topics) the Energy counter of the Xiaomi Smart Plug (EU) is now working corretly! Dont know why nur ist works now 👍

**Comment by dutchdevil83** [comment] 2020-10-18 10:11
> Thanks for the quick response.
> Good News: after some days (and several Home restarts due to other topics) the Energy counter of the Xiaomi Smart Plug (EU) is now working corretly! Dont know why nur ist works now 👍

That is good news. Next step is to get this integrated right with all meter values and ultimate step to get some "Maintenance Options" to reset the consumption meter values.

**Comment by TedTolboom** [comment] 2021-01-03 20:43
Optimized the initialization of the Aqara metering devices in v1.2.3; available in the app store test environment: https://homey.app/a/com.xiaomi-mi/test/

Should provide the solution to this issue; I'll close this issue for now, if persistent, please re-open

**Closed by TedTolboom** 2021-01-03 20:43 UTC
Labels: bug

**Comment by Niekvb-homey** [comment] 2021-07-30 19:02
Hi Ted,

I'm not sure if I'm allowed to comment on this issue with a "similar" issue:

I've got the "Aqara Smart Socket Plug" (**not the EU**, yeah I've got those too but those are working fine).
The Aqara Smart Socket Plug is not updating the total power consumption like stated above for the EU plug.

I've got 3 of those plugs and none are updating the total power.
One is showing "-" and the other two are stuck on a historic figure (I guess I used them previously with the Xiaomi app).
I want to use the data in combination with the "power by the hour" app but the app uses the total amount of power and therefore fails me.

I hope you can help out.

Aqara app version: V1.3.0
Homey version 7.1.0
