### ISSUE TITLE
Work Aqara Light Wall Switch Single/Double

### ISSUE THREAD

**Issue by Maxwell70** [TedTolboom/com.xiaomi-mi-zigbee#32] opened 2018-01-15 08:01 UTC
App 0.2.0, homey 1.5.4.-8.
Since last update double switches work better, but sometimes either there is no feedback from the physical enable/disable or I can't enable/disable on Homey.
Single switches were added well! Single switches worked a few times, and then stopped working completely!

**Comment by TedTolboom** [comment] 2018-01-15 08:49
@Maxwell70 trying to understand the issue.
You installed the master branch from GitHub after I announced the app update? 
Or earlier / development branch?

In the last app update, no changes have been made to these devices (or the meshdriver included in the app):
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/commits/master/drivers/sensor_86sw2Un/device.js

Since nothing changed, only the app update might have improved the situation.

Can you show the flows you use with this device?
These devices cannot be enabled / disabled on Homey because they act as a remote.
Only option, without ZigBee groups and scenes implemented in Homey FW, is to trigger a flow based on a single click (of either one of the buttons or the combination).

**Comment by Maxwell70** [comment] 2018-01-15 09:07
@TedTolboom I installed development 3 hours ago.
Today You added support single switch. And I tell you how single switch works.
The double switch did not work correctly until this update.
I haven't used flows yet.
I turn on/off the switches in Homey.

**Comment by TedTolboom** [comment] 2018-01-15 11:00
@Maxwell70 my mistake, still having the device of the other issue in mind...
Did you remove and re-install the devices after updating to 0.2.0?

Can you try running the app in debug mode (`athom project --run`), after enabling (removing the '//' in https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L11 and on https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L13)? 

To see if reports are being received by Homey..

**Comment by Maxwell70** [comment] 2018-01-15 11:05
@TedTolboom  After the upgrade I did not delete the device.

**Comment by Maxwell70** [comment] 2018-01-15 11:07
I've installed now the master

**Comment by Maxwell70** [comment] 2018-01-15 11:10
"Can you try running the app in debug mode (athom project --run), after enabling (removing the '//' in https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L11 and on https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/ctrl_neutral2/device.js#L13)?"
- I don't know how to start and what to do. Tell more!

**Comment by Maxwell70** [comment] 2018-01-15 11:12
I added a Dual-switch long ago. And the single switches I added after the upgrade.

**Comment by TedTolboom** [comment] 2018-01-15 11:47
I would advise to remove the double-switch and re-include it.

You have downloaded the GitHub release and installed it via `Athom project --install`...

Download the master branch on Github. 
Edit the `/drivers/ctrl_neutral2/device.js` file and remove the `//` to enable debug logging in line 11 and 13, save the file. 
Do the same for `/drivers/ctrl_neutral1/device.js`.
Now run the app in debug mode, via `Athom project --run`

Debug logging will now be visible in the terminal or command prompt.

When pressing a button on the device, it should show a response in the debug log.
If something strange is visible, please copy the log and post it here (as text file).
After your done, quit the app (CTRL-c) and reinstall it from app store or via `Athom project --install`

**Comment by Maxwell70** [comment] 2018-01-15 12:04
@TedTolboom I did the right thing?
[1.txt](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/files/1631534/1.txt)

**Comment by Maxwell70** [comment] 2018-01-15 12:36
Now the switches don't respond to clicks in Homey or reaction is applied in about a minute.

**Comment by Maxwell70** [comment] 2018-01-15 13:03
After reinstalling all the switches stopped working! The curtains ceased to be supported! :(((((

**Comment by TedTolboom** [comment] 2018-01-19 11:22
@Maxwell70 missed your response.
I don't think it went ok... I do see an error in the log, `SyntaxError: Unexpected identifier\`

In parallel, I delayed the release of 0.2.0 to be able to check the double switch myself...
Removed the switch and re-added it based on the 0.2.0 release and it responds to changes triggered by Homey and v.v.

Can you re-test based on the app store release?

Please include reference information:
- Are these switches working correctly at short distance of Homey?
- Add the ZigBee nodes table as shown on https://developer.athom.com/tools/zigbee

Regarding the curtains; these are deliberately still only available in the development branch...
All devices in the development branch (and not released as supported devices in the app store / master branch) are subject to change without prior notice (info shared on a closed channel). Installing the development branch is at your own risk.

**Comment by Maxwell70** [comment] 2018-01-19 11:27
Homey SW version - 1.5.4.-8
App version - 0.2.0 from AppStore
I was paired switches to the last update and tried it after the update.
The result of the work does not depend on the distance. I have the switches nearby to the Homey and far.

**Comment by Maxwell70** [comment] 2018-01-19 11:32
Add the ZigBee nodes table as shown on https://developer.athom.com/tools/zigbee
I do it

**Comment by Maxwell70** [comment] 2018-01-19 11:34
<img width="676" alt="2018-01-19 18 33 12" src="https://user-images.githubusercontent.com/33258356/35149069-58f1b504-fd47-11e7-809b-34bf43859ab2.png">

**Comment by Maxwell70** [comment] 2018-01-19 12:23
Please help me in solving this problem!

**Comment by TedTolboom** [comment] 2018-01-21 21:35
@Maxwell70 So the devices were already included before v0.2.0 was released?

Can you try to remove the switches from Homey and re-include the switches based on the v0.2.0 release? With the update to v0.2.0 the driver capabilities changed significantly; so that could explain the issue.

Tested the switch throughout the weekend here, but it is working ok. Same was confirmed by @addwindtan who proposed the driver change to make the switch work (including right switch).

**Comment by Maxwell70** [comment] 2018-01-22 00:01
I deleted all Zigbee devices. Reset network Zigbee. Then paired Homey with four switches (2 - single, 2 - double). First the switches are working fine, then do it incorrectly. Then do not work.
For all time of testing there was no case to all 4 switch was connected to Homey!
Photo After pairing:
<img width="655" alt="2018-01-22 6 59 38" src="https://user-images.githubusercontent.com/33258356/35200491-e3f14b78-ff41-11e7-98c6-c73e5bb01041.png">

**Comment by addwindtan** [comment] 2018-01-22 02:03
@Maxwell70 After you pair the single and the double switch, could you go to the settings page of the devices and capture the node information for us? I want to rule out that it could be a different model of the Xiaomi switch.

**Comment by Maxwell70** [comment] 2018-01-22 04:08
@addwindtan 
<img width="378" alt="2018-01-22 11 06 45" src="https://user-images.githubusercontent.com/33258356/35204992-9021691a-ff64-11e7-96fe-3cf54d9fd2e8.png">
<img width="342" alt="2018-01-22 11 07 04" src="https://user-images.githubusercontent.com/33258356/35204993-9048fa66-ff64-11e7-82d3-77eec5d7456a.png">
<img width="337" alt="2018-01-22 11 07 23" src="https://user-images.githubusercontent.com/33258356/35204994-906f17a0-ff64-11e7-8926-bbaa2b68cec5.png">
<img width="357" alt="2018-01-22 11 07 37" src="https://user-images.githubusercontent.com/33258356/35204995-9094e3ea-ff64-11e7-96ec-9093651b4055.png">

**Comment by Maxwell70** [comment] 2018-01-22 14:27
@addwindtan Is there a problem?
@TedTolboom You can help solve my problem?

**Comment by addwindtan** [comment] 2018-01-23 01:18
@Maxwell70 The node info is in order. I want to reproduce the problem on my end so that I can identify the problem. Could you confirm the steps below:

1. Paired Aqara double switch with Homey
2. Check the node map -> Aqara does not appear in node map

At first the switches work fine:
3. Press switch one and switch two on Aqara. The UI on Homey reflects the state correctly.
4. Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.

Wait for 5 minutes and try again. It does not work.
3. Press switch one and switch two on Aqara. The UI on Homey does not reflect the state correctly.
4. Toggle switch one and switch two on the UI. The lights wired to switch one and switch two does not on/off.

**Comment by Maxwell70** [comment] 2018-01-23 04:52
@addwindtan 
Paired double switch with Homey.
<img width="650" alt="2018-01-23 11 39 54" src="https://user-images.githubusercontent.com/33258356/35258449-2d0ffc78-0032-11e8-8c1b-f3fd0790600e.png">
Press switch one and switch two on Aqara. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Wait for 5 minutes.
Press switch one and switch two on Aqara. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.

**Comment by addwindtan** [comment] 2018-01-23 05:06
@Maxwell70 What you mentioned is the correct behaviour. How do you produce the issue?

**Comment by Maxwell70** [comment] 2018-01-23 05:10
@addwindtan 
Paired single switch with Homey.
<img width="640" alt="2018-01-23 11 55 19" src="https://user-images.githubusercontent.com/33258356/35258784-53b28f10-0034-11e8-9ef7-cef1aa8775f1.png">
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.
Wait for 5 minutes.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.

**Comment by Maxwell70** [comment] 2018-01-23 05:14
@addwindtan "What you mentioned is the correct behaviour. How do you produce the issue?"
I don't understand your question!

**Comment by addwindtan** [comment] 2018-01-23 05:23
@Maxwell70 
1. In order for me to find the solution, first I need to be able to re-create the problem in my lab.
2. What I require are the specific steps that led to you facing the problem
3. I will then try to follow the exact same steps that you did and see if I face the same problem over here in my lab.
4. Once I have the problem, I can step through the codes to find out what caused it.
5. Once I know the cause, I can implement the solution.

**Comment by Maxwell70** [comment] 2018-01-23 05:34
@addwindtan
Paired double switch with Homey.
<img width="610" alt="2018-01-23 12 18 54" src="https://user-images.githubusercontent.com/33258356/35259354-ec5e942c-0037-11e8-999f-41d08d828cb8.png">
<img width="930" alt="2018-01-23 12 19 04" src="https://user-images.githubusercontent.com/33258356/35259357-f52fe2b8-0037-11e8-98b8-be043a2181a8.png">
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Wait for 5 minutes.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.

**Comment by Maxwell70** [comment] 2018-01-23 05:53
@addwindtan
Paired single switch with Homey.
<img width="635" alt="2018-01-23 12 39 20" src="https://user-images.githubusercontent.com/33258356/35259833-9da5e65c-003a-11e8-8f42-98ef86305161.png">
<img width="931" alt="2018-01-23 12 39 32" src="https://user-images.githubusercontent.com/33258356/35259834-9dcb07ac-003a-11e8-8587-5585cde830d9.png">
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.

Being late when triggered sometimes 1-2 sec.

Wait for 5 minutes.

Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.
Press switch one and switch two on Aqara Double. The UI on Homey reflects the state correctly.
Toggle switch one and switch two on the UI. The lights wired to switch one and switch two turns on/off correctly.
Press switch on Aqara Single. The UI on Homey reflects the state correctly.
Toggle switch on the UI. The lights wired to switch turns on/off correctly.

Now wait about 1-2 hours .....

**Comment by Maxwell70** [comment] 2018-01-23 05:57
@addwindtan Question: why two switches always have no connection with Homey in node map?

**Comment by Maxwell70** [comment] 2018-01-23 12:41
@addwindtan Added two more double-switch.
<img width="628" alt="2018-01-23 19 35 07" src="https://user-images.githubusercontent.com/33258356/35276082-b699f902-0074-11e8-998d-d5880c7d0e7d.png">
All the switches work correctly.
Sometimes after long time not turns on/off on UI of Homey Toggle switch on the UI - the lights wired to switch turns on/off not correctly.

**Comment by addwindtan** [comment] 2018-01-23 13:57
@Maxwell70 Do you mean if you turn on via the UI, it actually turns off the switch?

**Comment by Maxwell70** [comment] 2018-01-23 14:01
@addwindtan Yes or no will work

**Comment by addwindtan** [comment] 2018-01-23 14:03
@Maxwell70 Sorry, i don't understand what you mean by "Yes or no will work"

**Comment by Maxwell70** [comment] 2018-01-23 14:08
@addwindtan if I turn on via the UI, it actually turns off the switch 
or if I turn on via the UI, it actually the switch does nothing

**Comment by addwindtan** [comment] 2018-01-23 14:31
@TedTolboom I did notice this problem when I first started working on the Xiaomi App. The status of the UI and the switch is not always in sync. Furthermore, when we send a command, we check the status on the UI (not on the switch), invert its status and send the zigbee command.

In Z-Wave, we would normally wait for an acknowledgement packet after every command to confirm it's been received and worked on. I think we will need to do something similar for Xiaomi switch too. However, I'm not quite sure which endpoint-cluster we can look at to get the state of the switch. Do you?

**Comment by Maxwell70** [comment] 2018-01-23 14:42
@addwindtan "The status of the UI and the switch is not always in sync." - I agree.
But sometimes the commands from the user interface are not enforced on the switch!

**Comment by TedTolboom** [comment] 2018-01-24 10:38
@addwindtan you’re right, the Xiaomi switch does not report its state, but provides a trigger... 
the Homey state is toggled in the driver...

If the device and Homey state differ, which might be caused by some latency in the network, then this might be interpreted as not functioning...

I would need to look into the reporting of the device with a Zigbee sniffer, to see if on another endpoint the device is reported... but will not have an option in the next three weeks (working abroad).

**Comment by Maxwell70** [comment] 2018-01-24 11:24
@TedTolboom @addwindtan Now I can't pair the seventh switch (double) .... Tried for about 20 times. Is this possible?

**Comment by addwindtan** [comment] 2018-01-24 13:43
@Maxwell70 It is unlikely to be the Xiaomi App issue. Perhaps you can check with guys at Athom if there's some sort of a limit.

**Comment by Maxwell70** [comment] 2018-01-25 00:47
@TedTolboom Checked. There is no limit.
Problem: New double switch from the box pair with MiHub - ok. After 15 minutes, I want to pair with Homey - not pair! I tried 30 times - not pair! Then I want to pair with MiHub - not pair. Now I can not pair switch with Homey and MiHub. What is the reason?

**Comment by Maxwell70** [comment] 2018-02-09 01:29
@TedTolboom Hi! Om r.11 Removal / addition fixed?

**Closed** 2019-09-16 21:40 UTC
