### ISSUE TITLE
Aquaria sensor temperature reporting

### ISSUE THREAD

**Issue by seblang** [TedTolboom/com.xiaomi-mi-zigbee#190] opened 2020-01-09 22:25 UTC
Since a fews days my sensor report 100° and its the same for all.
After restart no change.... Node are OK according admin site
![Screenshot_20200109_205826_app homey](https://user-images.githubusercontent.com/11487773/72109910-3d20d080-3337-11ea-9ec1-ff854ef79be5.jpg)

**Comment by TedTolboom** [comment] 2020-01-10 19:10
@seblang the diagnostics report submitted was done, directly after a reboot... but it does not contain any temperature reports to check the cause of the issue...

Can you submit a new report several hours after the reboot; so it should show some temp reporting?

> Note: this log has been manually submitted by a user.
>
> Log ID: d84d66a5-0edb-4ace-8506-ec36ca7c7e2b
> 
> User Message:
> -100°c for all temp srnsors
> 
> ---- stdout ----
> 2020-01-09 23:27:21 [log] [XiaomiZigbee] Xiaomi Zigbee app is running...
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet] [0] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [0] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [1] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [2] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [3] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [4] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [5] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [6] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [7] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_magnet.aq2] [8] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_motion] [0] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [weather] [0] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [weather] [1] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [weather] [2] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [weather] [3] ZigBeeDevice has been inited
> 2020-01-09 23:27:24 [log] [ManagerDrivers] [sensor_switch] [0] ZigBeeDevice has been inited
> 2020-01-09 23:27:31 [log] [ManagerDrivers] [sensor_magnet.aq2] [8] lifeline - battery 100
> 2020-01-09 23:27:31 [log] [ManagerDrivers] [sensor_magnet.aq2] [8] lifeline - contact alarm false
> 
> ---- stderr ----
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet] [0] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet] [0] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet.aq2] [0] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet.aq2] [1] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet.aq2] [0] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:27:54 [err] [ManagerDrivers] [sensor_magnet.aq2] [1] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [2] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [2] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [3] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [3] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [4] registerAttrReportListener() -> error could not configure attrReport_0_genOnOff_onOff { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }
> 2020-01-09 23:28:24 [err] [ManagerDrivers] [sensor_magnet.aq2] [4] failed to register attr report listener - genOnOff - Contact { Error: forced_timeout
>     at Remote IPC Process
>  message: 'forced_timeout' }

**Comment by TedTolboom** [comment] 2020-03-01 19:58
Should be fixed in 0.8.0. Otherwise, please reopen

**Closed by TedTolboom** 2020-03-01 19:58 UTC
