### ISSUE TITLE
Aqara Human Body Sensor timeout doesn t reset

### ISSUE THREAD

**Issue by MaximCrabbe** [TedTolboom/com.xiaomi-mi-zigbee#17] opened 2017-12-11 19:32 UTC
Disable motion alarm after: 5 (seconds). The text says: (when you go over the i in homey settings of the device)
"...Every time motion is observed by this device this timeout will reset.."
So I put it on 5 seconds, I start dancing in front off it and every 5 sec it will briefly jump off (the motion detection alarm) and turn back on. (So in the hallway the lights flash on and off realy quickly) However I can fix this with a countdown timer flow thingie however the text can be modified easily I guess?

**Comment by TedTolboom** [comment] 2018-01-14 11:47
@MaximCrabbe the motion sensor will cancel the motion_alarm the defined time (in `Disable motion alarm after` parameter) after the **last** motion has been detected.

Below logging shows the example where 30 seconds (parameter in my case) after the motion detection:
```
2018-01-14 12:38:30 [log] [ManagerDrivers] [sensor_motion.aq2] [0] measure_luminance 2
2018-01-14 12:38:30 [log] [ManagerDrivers] [sensor_motion.aq2] [0] alarm_motion true
2018-01-14 12:39:00 [log] [ManagerDrivers] [sensor_motion.aq2] [0] manual alarm_motion reset
```
So the motion timeout reset works as intended...

Can you clarify the issue?

**Comment by brtwrs** [comment] 2018-01-30 09:40
Hi, Im also experiencing this. Some of my sensors are working perfect, but others don't reset the timer and the alarm turns off and on again after the giving seconds. Even if I keep moving around in front of the sensor

**Comment by HRFST** [comment] 2018-01-30 20:55
Hi, I find something. I have 2 brand new 'Aqara Human body sensor'  connect with homey,
The sensor timer does reset after 60 seconds. But not during the first 60 seconds!

So when timer is 80 seconds.
After 60 seconds it can be reset and will run 80 seconds again.

Do you know if the 60 seconds wait before motion is detected is a hardware limitation from the sensor or is it in your software?

My problem is that I can't use the sensor for faster motion detection.

Any ideas?

**Comment by cbho** [comment] 2018-01-30 21:01
Already described here: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/34

**Comment by HRFST** [comment] 2018-01-30 21:29
@cbho so the 60sec blind time is in the hardware of the Aqara sensor?

**Comment by cbho** [comment] 2018-01-30 22:25
Unfortunately, yes...

**Comment by TedTolboom** [comment] 2018-02-15 06:40
As also commented in the forum: https://forum.athom.com/discussion/comment/67188/#Comment_67188

I also recently learned that the sensors have 2 different modes:
Normal and test mode, as described in the FAQ of Gearbest:

This does explain why the sensors work with 5 second interval directly (first 2 hours) after inclusion and when the button has been pressed... and fall back to the 1 minute interval after the 2 hours. 

So this is a device (firmware) limitation. 
I'll update the minimum interval value in the next update accordingly and will close this issue.

**Closed by TedTolboom** 2018-02-15 06:40 UTC
Labels: waiting for user feedback
