### ISSUE TITLE
...so i´m another one with zigbee smart switch :) 

### ISSUE THREAD

**Issue by Hilox** [TedTolboom/com.xiaomi-mi-zigbee#90] opened 2018-09-24 15:11 UTC
Hi, i also purchased a aqara smart switch and when added to homey with the zigbee-app it shows as an unknown device. 
Link to product: https://www.aliexpress.com/item/Xiaomi-Mijia-Aqara-Smart-Wireless-Switch-Smart-Remote-One-Key-Control-Aqara-Intelligent-Application-Home-Security/32868964085.html?spm=a2g0s.9042311.0.0.b5cf4c4d9YL7yN 

![image](https://user-images.githubusercontent.com/43545531/45960217-02006e00-c01c-11e8-9fbc-c79f63a36775.png)

Info On the backside: 
WXKG11LM
CMIIT ID: 2016DP6422

Not shure if i need to open an issue as i can see that the backside info corresponds with the pic in #89  but i´ll be happy to get this going :) 

/Marius

**Comment by TedTolboom** [comment] 2018-09-25 15:43
@Hilox that's a confirmed duplicate of #89, I'll close this one and follow-up on #89 
Please also see: https://community.athom.com/t/xiaomi-aqara-smart-home-zigbee-app-v0-4-1/156/57

**Closed by TedTolboom** 2018-09-25 15:43 UTC
