### ISSUE TITLE
LIMIT of adding Xiaomi-mi sensors to Homey?

### ISSUE THREAD

**Issue by OWillekens** [TedTolboom/com.xiaomi-mi-zigbee#16] opened 2017-12-02 12:15 UTC
Is there a LIMIT of adding Xiaomi-mi sensors to Homey? I've installed the new update of the Homey software and I've added without any problems many TEMP/HUM sensors, wireless SWITCHES, OCCUPANCY sensors and some DOOR contacts. After adding the last 6 DOOR contacts, I can not add extra DOOR contacts to Homey anymore. The adding procedure is well known and I've tried different DOOR contacts to add extra, without success. I still need to add >10 extra Xiaomi sensors and there are 150 sensors installed already on my Homey (see uploaded pictures).
Thank you for your help.
<img width="2298" alt="schermafbeelding 2017-12-02 om 13 10 00" src="https://user-images.githubusercontent.com/20577141/33515376-ace5c94e-d762-11e7-9572-b000a8b9644a.png">
<img width="2296" alt="schermafbeelding 2017-12-02 om 13 10 15" src="https://user-images.githubusercontent.com/20577141/33515377-acfc3878-d762-11e7-8f8e-4f2236dff6a8.png">

**Comment by TedTolboom** [comment] 2017-12-04 08:37
Hi @OWillekens, 

There are no limits I added in the Xiaomi app in the amount of devices you are able to add to Homey.
I suspect you are running on 1.5.4 or 1.5.5 Homey SW release. Correct?

Athom is currently working on 1.5.6 which is (I'm currently testing it) significantly improving speed on the Z-wave and Zigbee radio's. I don't have a timing when 1.5.6 will be released to experimental.

What you could try to do is to Pull the Plug of Homey for about 15 minutes, let Homey start-up completely (can take 15-30 minutes before all apps are initialized) and then try to re-include the sensor(s) in proximity of Homey

**Comment by OWillekens** [comment] 2017-12-04 19:44
Hi Ted, 
Many thanks for your feedback. I really appreciate this, because Xiaomi has many low cost sensors! My Homey is running on 1.5.4.
I have tried to pull the plug of Homey for >15min and then restart Homey.
Then I have tried again to add/couple 3 Xiaomi door sensors with Homey, without succes. Still the same result, no Zigbee sensor found.
Do you have other recommendations?
P.S. Athom replied that there is NO limit of sensors which you can connect to Homey, so probably it seems a Xiaomi sensor issue. It went smooth until sensor ..25, and then suddenly I could add no extra sensors anymore.
End of this week I can try to add another brand of sensor (Neo Coolcam) to Homey, but currently I have no new sensors anymore to test with, only 5 extra Xiaomi door sensors which can not be connected with my Homey.
Olivier

**Comment by OWillekens** [comment] 2017-12-09 09:44
Hi Ted,
Do you have other recommendations?
Homey has NO limits in adding devices/sensors. Has he Xiaomi app limits in adding sensors?
Also removing the battery in the last sensors is not solving the issue. Restart Homey is also no solution.
Hopefully I can try a last test next week when I receive some extra Neo Coolcam sensors. If I can add extra Neo Coolcam sensors, then I would state that something is limiting in the Xiaomo Mi APP is blocking the installation process of extra sensors to Homey. Can you agree?
Olivier

**Comment by TedTolboom** [comment] 2017-12-11 08:32
Hi Olivier,

Neo Coolcam sensors are Z-wave based, while the Xiaomi are Zigbee based.
In the Xiaomi Mi Zigbee app there are no limits blocking the addition of more sensors. 

I do suspect that it is an issue that is caused by the Zigbee core (bandwith of the communication between Z-wave **and** Zigbee chip). This is a known issue.

Athom is going to release 1.5.6-RC5 to the experimental channel today.
I've tested 1.5.6 within the developer-preview channel and bandwidth is increased significantly and a number of issues (including inclusion issues) are solved in this release.

Can you try to add these sensors when you updated your Homey to 1.5.6?

**Comment by OWillekens** [comment] 2017-12-11 10:46
Hi Ted,
Thank you for your feedback on GitHub. My Homey is currently on 1.5.4.
I can not upgrade my Homey, because he can not find any experimental upgrade 1.5.6. Can you let me know how I can install this upgrade 1.5.6, so I can test to add more Zigbee (Xiaomi) sensors to my Homey?
It is strange that Athom people told me that there is no limit for adding sensors and there is no issue known, but if I read your feedback, Athom is working on new software upgrade to solve issues with inclusion and bandwith between Z-Wave + Zigbee chip. So they are aware of issues, but unfortunately they are not talking about it our giving any solutions. Homey is a wonderfull product, but when Athom is not supporting openly about known issues, it may change their unique position in the market. Olivier

**Comment by TedTolboom** [comment] 2017-12-11 15:23
Hi Olivier,

1.5.6-RC6 should be available again for downloading in experimental updates: see https://firmware.athom.com/  So you should be able to update and test if this solves the problem.

On the communication with Athom; I will forward this feedback to Bram, the community manager at Athom, also handling most of the support requests. I guess we both can be right but still not solve your issue... which might be related to the wording "limits". At both the Homey core as well as the Xiaomi Mi Zigbee app _no limits are set_ to limit the amount of devices being able to add... 

But still something is preventing you from adding additional sensors... 
which needs to be understood and solved...

First step would be to check if the increased bandwidth and other ZigBee related stability improvements of 1.5.6-RC6 does solve the issue...

**Comment by OWillekens** [comment] 2017-12-11 20:46
Hi Ted, unfortunately I can not install/download any new update from the https://firmware.athom.com/ website. What am I doing wrong? How can I download the proper update to install on my Homey?
Olivier

**Comment by OWillekens** [comment] 2017-12-11 20:46
Hi Ted, unfortunately I can not install/download any new update from the https://firmware.athom.com/ website. What am I doing wrong? How can I download the proper update to install on my Homey?
Olivier

**Comment by OWillekens** [comment] 2017-12-11 22:11
Hi Ted, I'm sorry, in Homey I could see now the update 1.5.6-RC6, so I have installed this update. Unfortunately, this upgrade brought no solution. Still "no zigbee devices" found. So no extra Xiaomi doorsensors could be installed. Olivier

**Comment by OWillekens** [comment] 2017-12-12 20:46
Hi Ted, I have received today and added successfully 1x Neo Coolcam PIR sensor to Homey (Z-Wave) without any problem. So Homey seems not be the problem, and adding extra Z-Wave sensors is successful. Adding an extra Xiaomi device/sensor (Zigbee) is NOT working. What is your advice?
Olivier

**Comment by TedTolboom** [comment] 2017-12-13 12:43
Hi Olivier,

To get a better understanding of you issue, can you share the screenshots of the Nodes tables for Zigbee and Z-wave of your Homey? 
As shown on: https://developer.athom.com/tools/zigbee and https://developer.athom.com/tools/zwave

Together with a list of which devices (type and amount) you are still not able to include..

**Comment by OWillekens** [comment] 2017-12-25 19:29
Hi Ted,

I was out of the office for almost 2 weeks, and I have found some time to take a screenshot of the NODES table for Zigbee of my Homey (see annex).
I was successful in adding 10 extra Z-Wave (10x Neo Coolcam doorcontacts) sensors 2 days ago (see I have NOT added a screenshot of the Z-Wave Nodes table), but still I can NOT add any Zigbee device after I was successful for several Xiaomi devices/sensors (PIR sensors, TEMP sensors, doorcontacts) => see Zigbee NODES table (currently 21-1 Homey = 20 external Zigbee devices connected => I would check if there is NO limit on the amount of Zigbee devices for example 20 pieces => Athom tells me there is NO limit for Homey in adding/connecting Zigbee or Z-Wave sensors).

Within the Xiaomi Mi Zigbee app, I can NOT add any sensors anymore. I have tested over 25 times without succes.
Even if I open the Homey app and select Zigbee protocol, Homey is NOT finding any other Zigbee device.
Currently my Homey is running on 1.5.6-RC7.
I still need to add 5x extra Zigbee window/door sensors of Xiaomi + approx. 15x Yeelight Xiaomi light bulbs (white + RGB).

I do hope you can find the root-cause of this problem, so I can add new Xiaomi sensors and light bulbs soon.
Many thanks for your help.



Kindest regards,

Olivier Willekens
E: olivierwillekens@telenet.be

**Comment by TedTolboom** [comment] 2018-02-15 06:36
Hi Olivier,

See the response Athom provided in the by @captkiwi referenced issue:
https://github.com/athombv/homey/issues/2160

Homey currently uses a limitation of 20 end-devices (battery powered sensors) if no additional routers (mains powered ZigBee devices like light bulbs or sockets) are connected.

"adding routers to a zigbee network will increase the maximum number of connectable end devices."

I hope this answers your questions.
I will close this issue for now.

**Closed by TedTolboom** 2018-02-15 06:36 UTC
